package com.tisson.dao.bis;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.tisson.entity.bis.CumAcct;

public interface CumAcctMapper {
	

//	@Select("select acct_code from t_cum_acct t where t.cust_id = (select a.cust_id"
//			+" from t_cum_info a where a.cust_code = ?) and t.acct_type=?")
//	String getAcctCode(String payeeCode, String string);

	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_ACCT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int deleteByPrimaryKey(Long acctId);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_ACCT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int insert(CumAcct record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_ACCT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int insertSelective(CumAcct record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_ACCT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	CumAcct selectByPrimaryKey(Long acctId);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_ACCT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int updateByPrimaryKeySelective(CumAcct record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_ACCT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int updateByPrimaryKey(CumAcct record);


	/**
	 * 通过客户编码查询银行卡号
	 */
	@Select("select acct_code from t_cum_acct t where t.cust_id = (select a.cust_id"
			  +" from t_cum_info a where a.cust_code = #{custCode}) and t.acct_type='ACCT002'")
	public String getAcctCode(@Param("custCode")String custCode);
	

	/**
	 * 通过银行卡号查询银行编码
	 * @param acctCode
	 * @return bankCode
	 */
//	@Select("select bank_code from t_sym_bankcard where account_prefix like '#{f}%' and account_length=?")
//	String getBankCode(@Param("acctCode")String acctCode,@Param("acctType") Integer acctType);
	 String getBankCode(String acctCode,Integer acctType);
		
	
	/**
	 * 通过客户编码查询【母卡�?银行卡号
	 */
	@Select("select acct.ACCT_CODE from t_cum_info info1,t_cum_acct acct where"
			+ " info1.cust_id=acct.cust_id and acct.acct_type='ACCT002' and info1.cust_type='C02'and info1.prtn_id= (select p.parent_id from t_cum_info info, t_pnm_partner p  where  info.prtn_id= p.prtn_id and info.cust_code=#{custCode})")
	public String getParentAcctCode(@Param("custCode")String custCode);
}