package com.tisson.dao.bis;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.tisson.entity.bis.CumAttr;
import com.tisson.entity.bis.CumAttrKey;

public interface CumAttrMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_ATTR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int deleteByPrimaryKey(CumAttrKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_ATTR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int insert(CumAttr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_ATTR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int insertSelective(CumAttr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_ATTR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	CumAttr selectByPrimaryKey(CumAttrKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_ATTR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int updateByPrimaryKeySelective(CumAttr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_ATTR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int updateByPrimaryKey(CumAttr record);

	@Select("SELECT AA.VALUE1 FROM  T_CUM_ATTR AA WHERE AA.ATTR_ID=4224 AND "
			+ "AA.CUST_ID=(SELECT C.CUST_ID FROM T_CUM_INFO C WHERE C.CUST_CODE=#{custCode} "
			+ "AND C.CUST_TYPE='C02')")
	public String getPlineIdByCusCode(@Param("custCode")String custCode);
}