package com.tisson.dao.bis;

import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.tisson.entity.bis.CumInfo;

public interface CumInfoMapper {
	

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_INFO
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int deleteByPrimaryKey(Long custId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_INFO
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int insert(CumInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_INFO
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int insertSelective(CumInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_INFO
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	CumInfo selectByPrimaryKey(Long custId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_INFO
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int updateByPrimaryKeySelective(CumInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_INFO
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int updateByPrimaryKey(CumInfo record);

	@Select("select info.cust_id from t_cum_info info where info.cust_code=#{custCode}")
	String getCustIdByCode(@Param("custCode") String custCode);

	@Select("select tmn.TERM_CODE, info.CUST_CODE  from T_TMN_INFO tmn, T_CUM_INFO info, "
			+ "T_CUM_CHANNEL cc where tmn.ex_termcode = #{tmnNum}  and CC.TERM_ID = tmn.TERM_ID "
			+ "  and info.CUST_ID = cc.CUST_ID   and tmn.STAT = 'S0A'")
	Map<String, String> getCustCodeByExtTermNumNo(@Param("tmnNum") String tmnNum);

	@Select("select prtn_code from t_pnm_partner p where p.prtn_type='PT403' start with p.prtn_id="
			+ "(select i.prtn_Id from t_cum_info i where i.cust_type='C02' and i.cust_code=#{custCode})"
			+ " connect by prior p.parent_id=p.prtn_id")
	String getMerIdByCustCode(@Param("custCode")String custCode);

}
