package com.tisson.dao.bis;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.tisson.entity.bis.CumObj;

public interface CumObjMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_OBJ
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int deleteByPrimaryKey(Long objId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_OBJ
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int insert(CumObj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_OBJ
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int insertSelective(CumObj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_OBJ
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	CumObj selectByPrimaryKey(Long objId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_OBJ
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int updateByPrimaryKeySelective(CumObj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_OBJ
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int updateByPrimaryKey(CumObj record);

	@Select("select obj_code from t_cum_obj o  where o.prod_id=200 and o.cust_id in "
				+ "(select i.cust_id from t_cum_info i where i.prtn_id=(select prtn_id from t_pnm_partner where prtn_code=#{merId})) and o.stat='S0A'")
	public List<Map<String, String>> getRelationMerId(@Param("merId")String merId);
}