package com.tisson.dao.bis;

import com.tisson.entity.bis.CumRegbindCard;

public interface CumRegbindCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUM_REGBINDCARD
     *
     * @mbggenerated Mon Jan 27 13:59:45 CST 2014
     */
    int deleteByPrimaryKey(Long bindId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUM_REGBINDCARD
     *
     * @mbggenerated Mon Jan 27 13:59:45 CST 2014
     */
    int insert(CumRegbindCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUM_REGBINDCARD
     *
     * @mbggenerated Mon Jan 27 13:59:45 CST 2014
     */
    int insertSelective(CumRegbindCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUM_REGBINDCARD
     *
     * @mbggenerated Mon Jan 27 13:59:45 CST 2014
     */
    CumRegbindCard selectByPrimaryKey(Long bindId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUM_REGBINDCARD
     *
     * @mbggenerated Mon Jan 27 13:59:45 CST 2014
     */
    int updateByPrimaryKeySelective(CumRegbindCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUM_REGBINDCARD
     *
     * @mbggenerated Mon Jan 27 13:59:45 CST 2014
     */
    int updateByPrimaryKey(CumRegbindCard record);
}