package com.tisson.dao.bis;

import com.tisson.entity.bis.SymError;
import com.tisson.entity.bis.SymErrorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SymErrorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SYM_ERROR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int countByExample(SymErrorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SYM_ERROR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int deleteByExample(SymErrorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SYM_ERROR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int deleteByPrimaryKey(String errorCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SYM_ERROR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int insert(SymError record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SYM_ERROR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int insertSelective(SymError record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SYM_ERROR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	List<SymError> selectByExample(SymErrorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SYM_ERROR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	SymError selectByPrimaryKey(String errorCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SYM_ERROR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int updateByExampleSelective(@Param("record") SymError record,
			@Param("example") SymErrorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SYM_ERROR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int updateByExample(@Param("record") SymError record,
			@Param("example") SymErrorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SYM_ERROR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int updateByPrimaryKeySelective(SymError record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SYM_ERROR
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	int updateByPrimaryKey(SymError record);
}