package com.tisson.entity.bis;

public class CumAttrKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_ATTR.CUST_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private Long custId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_ATTR.ATTR_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private Long attrId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_ATTR.CUST_ID
	 * @return  the value of T_CUM_ATTR.CUST_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public Long getCustId() {
		return custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_ATTR.CUST_ID
	 * @param custId  the value for T_CUM_ATTR.CUST_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setCustId(Long custId) {
		this.custId = custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_ATTR.ATTR_ID
	 * @return  the value of T_CUM_ATTR.ATTR_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public Long getAttrId() {
		return attrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_ATTR.ATTR_ID
	 * @param attrId  the value for T_CUM_ATTR.ATTR_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setAttrId(Long attrId) {
		this.attrId = attrId;
	}
}