package com.tisson.entity.bis;

public class CumAttr extends CumAttrKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_ATTR.VALUE1
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String value1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_ATTR.VALUE2
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String value2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_ATTR.STAT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String stat;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_ATTR.VALUE1
	 * @return  the value of T_CUM_ATTR.VALUE1
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getValue1() {
		return value1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_ATTR.VALUE1
	 * @param value1  the value for T_CUM_ATTR.VALUE1
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setValue1(String value1) {
		this.value1 = value1 == null ? null : value1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_ATTR.VALUE2
	 * @return  the value of T_CUM_ATTR.VALUE2
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getValue2() {
		return value2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_ATTR.VALUE2
	 * @param value2  the value for T_CUM_ATTR.VALUE2
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setValue2(String value2) {
		this.value2 = value2 == null ? null : value2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_ATTR.STAT
	 * @return  the value of T_CUM_ATTR.STAT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getStat() {
		return stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_ATTR.STAT
	 * @param stat  the value for T_CUM_ATTR.STAT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setStat(String stat) {
		this.stat = stat == null ? null : stat.trim();
	}
}