package com.tisson.entity.bis;

import java.util.Date;

public class CumInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.CUST_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private Long custId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.CUST_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String custCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.CUST_TYPE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String custType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.CUST_SEX
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String custSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.CUST_NAME
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String custName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.CUST_PWD
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String custPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.AREA_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String areaCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.CERT_TYPE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String certType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.CERT_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String certCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.PRTN_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private Long prtnId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.VIP_LEV
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String vipLev;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.AUTH_LEV
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String authLev;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.EFF_DATE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private Date effDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.EXP_DATE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private Date expDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.STAT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String stat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.OPER_FLAG
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String operFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.BUSI_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String busiCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.SVR_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String svrCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.TAXES_FLAG
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String taxesFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.ACTION_TYPE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String actionType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_INFO.CHANNEL_TYPE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String channelType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.CUST_ID
	 * @return  the value of T_CUM_INFO.CUST_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public Long getCustId() {
		return custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.CUST_ID
	 * @param custId  the value for T_CUM_INFO.CUST_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setCustId(Long custId) {
		this.custId = custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.CUST_CODE
	 * @return  the value of T_CUM_INFO.CUST_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getCustCode() {
		return custCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.CUST_CODE
	 * @param custCode  the value for T_CUM_INFO.CUST_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setCustCode(String custCode) {
		this.custCode = custCode == null ? null : custCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.CUST_TYPE
	 * @return  the value of T_CUM_INFO.CUST_TYPE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getCustType() {
		return custType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.CUST_TYPE
	 * @param custType  the value for T_CUM_INFO.CUST_TYPE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setCustType(String custType) {
		this.custType = custType == null ? null : custType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.CUST_SEX
	 * @return  the value of T_CUM_INFO.CUST_SEX
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getCustSex() {
		return custSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.CUST_SEX
	 * @param custSex  the value for T_CUM_INFO.CUST_SEX
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setCustSex(String custSex) {
		this.custSex = custSex == null ? null : custSex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.CUST_NAME
	 * @return  the value of T_CUM_INFO.CUST_NAME
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getCustName() {
		return custName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.CUST_NAME
	 * @param custName  the value for T_CUM_INFO.CUST_NAME
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setCustName(String custName) {
		this.custName = custName == null ? null : custName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.CUST_PWD
	 * @return  the value of T_CUM_INFO.CUST_PWD
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getCustPwd() {
		return custPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.CUST_PWD
	 * @param custPwd  the value for T_CUM_INFO.CUST_PWD
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setCustPwd(String custPwd) {
		this.custPwd = custPwd == null ? null : custPwd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.AREA_CODE
	 * @return  the value of T_CUM_INFO.AREA_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getAreaCode() {
		return areaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.AREA_CODE
	 * @param areaCode  the value for T_CUM_INFO.AREA_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode == null ? null : areaCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.CERT_TYPE
	 * @return  the value of T_CUM_INFO.CERT_TYPE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getCertType() {
		return certType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.CERT_TYPE
	 * @param certType  the value for T_CUM_INFO.CERT_TYPE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setCertType(String certType) {
		this.certType = certType == null ? null : certType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.CERT_CODE
	 * @return  the value of T_CUM_INFO.CERT_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getCertCode() {
		return certCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.CERT_CODE
	 * @param certCode  the value for T_CUM_INFO.CERT_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setCertCode(String certCode) {
		this.certCode = certCode == null ? null : certCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.PRTN_ID
	 * @return  the value of T_CUM_INFO.PRTN_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public Long getPrtnId() {
		return prtnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.PRTN_ID
	 * @param prtnId  the value for T_CUM_INFO.PRTN_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setPrtnId(Long prtnId) {
		this.prtnId = prtnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.VIP_LEV
	 * @return  the value of T_CUM_INFO.VIP_LEV
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getVipLev() {
		return vipLev;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.VIP_LEV
	 * @param vipLev  the value for T_CUM_INFO.VIP_LEV
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setVipLev(String vipLev) {
		this.vipLev = vipLev == null ? null : vipLev.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.AUTH_LEV
	 * @return  the value of T_CUM_INFO.AUTH_LEV
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getAuthLev() {
		return authLev;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.AUTH_LEV
	 * @param authLev  the value for T_CUM_INFO.AUTH_LEV
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setAuthLev(String authLev) {
		this.authLev = authLev == null ? null : authLev.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.EFF_DATE
	 * @return  the value of T_CUM_INFO.EFF_DATE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public Date getEffDate() {
		return effDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.EFF_DATE
	 * @param effDate  the value for T_CUM_INFO.EFF_DATE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setEffDate(Date effDate) {
		this.effDate = effDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.EXP_DATE
	 * @return  the value of T_CUM_INFO.EXP_DATE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public Date getExpDate() {
		return expDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.EXP_DATE
	 * @param expDate  the value for T_CUM_INFO.EXP_DATE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.STAT
	 * @return  the value of T_CUM_INFO.STAT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getStat() {
		return stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.STAT
	 * @param stat  the value for T_CUM_INFO.STAT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setStat(String stat) {
		this.stat = stat == null ? null : stat.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.OPER_FLAG
	 * @return  the value of T_CUM_INFO.OPER_FLAG
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getOperFlag() {
		return operFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.OPER_FLAG
	 * @param operFlag  the value for T_CUM_INFO.OPER_FLAG
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setOperFlag(String operFlag) {
		this.operFlag = operFlag == null ? null : operFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.BUSI_CODE
	 * @return  the value of T_CUM_INFO.BUSI_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getBusiCode() {
		return busiCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.BUSI_CODE
	 * @param busiCode  the value for T_CUM_INFO.BUSI_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setBusiCode(String busiCode) {
		this.busiCode = busiCode == null ? null : busiCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.SVR_CODE
	 * @return  the value of T_CUM_INFO.SVR_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getSvrCode() {
		return svrCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.SVR_CODE
	 * @param svrCode  the value for T_CUM_INFO.SVR_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setSvrCode(String svrCode) {
		this.svrCode = svrCode == null ? null : svrCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.TAXES_FLAG
	 * @return  the value of T_CUM_INFO.TAXES_FLAG
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getTaxesFlag() {
		return taxesFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.TAXES_FLAG
	 * @param taxesFlag  the value for T_CUM_INFO.TAXES_FLAG
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setTaxesFlag(String taxesFlag) {
		this.taxesFlag = taxesFlag == null ? null : taxesFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.ACTION_TYPE
	 * @return  the value of T_CUM_INFO.ACTION_TYPE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getActionType() {
		return actionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.ACTION_TYPE
	 * @param actionType  the value for T_CUM_INFO.ACTION_TYPE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setActionType(String actionType) {
		this.actionType = actionType == null ? null : actionType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_INFO.CHANNEL_TYPE
	 * @return  the value of T_CUM_INFO.CHANNEL_TYPE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getChannelType() {
		return channelType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_INFO.CHANNEL_TYPE
	 * @param channelType  the value for T_CUM_INFO.CHANNEL_TYPE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setChannelType(String channelType) {
		this.channelType = channelType == null ? null : channelType.trim();
	}
}