package com.tisson.entity.bis;

public class CumObj {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_OBJ.OBJ_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private Long objId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_OBJ.CUST_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private Long custId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_OBJ.PROD_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String prodId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_OBJ.OBJ_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String objCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_OBJ.STAT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String stat;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_OBJ.OBJ_ID
	 * @return  the value of T_CUM_OBJ.OBJ_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public Long getObjId() {
		return objId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_OBJ.OBJ_ID
	 * @param objId  the value for T_CUM_OBJ.OBJ_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setObjId(Long objId) {
		this.objId = objId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_OBJ.CUST_ID
	 * @return  the value of T_CUM_OBJ.CUST_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public Long getCustId() {
		return custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_OBJ.CUST_ID
	 * @param custId  the value for T_CUM_OBJ.CUST_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setCustId(Long custId) {
		this.custId = custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_OBJ.PROD_ID
	 * @return  the value of T_CUM_OBJ.PROD_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getProdId() {
		return prodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_OBJ.PROD_ID
	 * @param prodId  the value for T_CUM_OBJ.PROD_ID
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setProdId(String prodId) {
		this.prodId = prodId == null ? null : prodId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_OBJ.OBJ_CODE
	 * @return  the value of T_CUM_OBJ.OBJ_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getObjCode() {
		return objCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_OBJ.OBJ_CODE
	 * @param objCode  the value for T_CUM_OBJ.OBJ_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setObjCode(String objCode) {
		this.objCode = objCode == null ? null : objCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_OBJ.STAT
	 * @return  the value of T_CUM_OBJ.STAT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getStat() {
		return stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_OBJ.STAT
	 * @param stat  the value for T_CUM_OBJ.STAT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setStat(String stat) {
		this.stat = stat == null ? null : stat.trim();
	}
}