package com.tisson.entity.bis;

import java.util.Date;

public class RegbindCard {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.BIND_ID
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private Long bindId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.REG_ID
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private Long regId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.STAFF_CODE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private String staffCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.CUST_CODE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private String custCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.BIND_DATE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private Date bindDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.BIND_ORDERNO
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private String bindOrderno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.BIND_STATE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private String bindState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.BANK_CODE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private String bankCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.BANK_NAME
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private String bankName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.BANK_OPEN
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private String bankOpen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.AREA_CODE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private String areaCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.BANK_ACCT
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private String bankAcct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.TRANSACC_NAME
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private String transaccName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.CER_NO
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private String cerNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.OPEN_PHONE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private String openPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.STAT
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private String stat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUM_REGBINDCARD.REMARK
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.BIND_ID
	 * @return  the value of T_CUM_REGBINDCARD.BIND_ID
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public Long getBindId() {
		return bindId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.BIND_ID
	 * @param bindId  the value for T_CUM_REGBINDCARD.BIND_ID
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setBindId(Long bindId) {
		this.bindId = bindId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.REG_ID
	 * @return  the value of T_CUM_REGBINDCARD.REG_ID
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public Long getRegId() {
		return regId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.REG_ID
	 * @param regId  the value for T_CUM_REGBINDCARD.REG_ID
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setRegId(Long regId) {
		this.regId = regId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.STAFF_CODE
	 * @return  the value of T_CUM_REGBINDCARD.STAFF_CODE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public String getStaffCode() {
		return staffCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.STAFF_CODE
	 * @param staffCode  the value for T_CUM_REGBINDCARD.STAFF_CODE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setStaffCode(String staffCode) {
		this.staffCode = staffCode == null ? null : staffCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.CUST_CODE
	 * @return  the value of T_CUM_REGBINDCARD.CUST_CODE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public String getCustCode() {
		return custCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.CUST_CODE
	 * @param custCode  the value for T_CUM_REGBINDCARD.CUST_CODE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setCustCode(String custCode) {
		this.custCode = custCode == null ? null : custCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.BIND_DATE
	 * @return  the value of T_CUM_REGBINDCARD.BIND_DATE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public Date getBindDate() {
		return bindDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.BIND_DATE
	 * @param bindDate  the value for T_CUM_REGBINDCARD.BIND_DATE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setBindDate(Date bindDate) {
		this.bindDate = bindDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.BIND_ORDERNO
	 * @return  the value of T_CUM_REGBINDCARD.BIND_ORDERNO
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public String getBindOrderno() {
		return bindOrderno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.BIND_ORDERNO
	 * @param bindOrderno  the value for T_CUM_REGBINDCARD.BIND_ORDERNO
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setBindOrderno(String bindOrderno) {
		this.bindOrderno = bindOrderno == null ? null : bindOrderno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.BIND_STATE
	 * @return  the value of T_CUM_REGBINDCARD.BIND_STATE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public String getBindState() {
		return bindState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.BIND_STATE
	 * @param bindState  the value for T_CUM_REGBINDCARD.BIND_STATE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setBindState(String bindState) {
		this.bindState = bindState == null ? null : bindState.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.BANK_CODE
	 * @return  the value of T_CUM_REGBINDCARD.BANK_CODE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public String getBankCode() {
		return bankCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.BANK_CODE
	 * @param bankCode  the value for T_CUM_REGBINDCARD.BANK_CODE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setBankCode(String bankCode) {
		this.bankCode = bankCode == null ? null : bankCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.BANK_NAME
	 * @return  the value of T_CUM_REGBINDCARD.BANK_NAME
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public String getBankName() {
		return bankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.BANK_NAME
	 * @param bankName  the value for T_CUM_REGBINDCARD.BANK_NAME
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setBankName(String bankName) {
		this.bankName = bankName == null ? null : bankName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.BANK_OPEN
	 * @return  the value of T_CUM_REGBINDCARD.BANK_OPEN
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public String getBankOpen() {
		return bankOpen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.BANK_OPEN
	 * @param bankOpen  the value for T_CUM_REGBINDCARD.BANK_OPEN
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setBankOpen(String bankOpen) {
		this.bankOpen = bankOpen == null ? null : bankOpen.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.AREA_CODE
	 * @return  the value of T_CUM_REGBINDCARD.AREA_CODE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public String getAreaCode() {
		return areaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.AREA_CODE
	 * @param areaCode  the value for T_CUM_REGBINDCARD.AREA_CODE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode == null ? null : areaCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.BANK_ACCT
	 * @return  the value of T_CUM_REGBINDCARD.BANK_ACCT
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public String getBankAcct() {
		return bankAcct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.BANK_ACCT
	 * @param bankAcct  the value for T_CUM_REGBINDCARD.BANK_ACCT
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setBankAcct(String bankAcct) {
		this.bankAcct = bankAcct == null ? null : bankAcct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.TRANSACC_NAME
	 * @return  the value of T_CUM_REGBINDCARD.TRANSACC_NAME
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public String getTransaccName() {
		return transaccName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.TRANSACC_NAME
	 * @param transaccName  the value for T_CUM_REGBINDCARD.TRANSACC_NAME
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setTransaccName(String transaccName) {
		this.transaccName = transaccName == null ? null : transaccName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.CER_NO
	 * @return  the value of T_CUM_REGBINDCARD.CER_NO
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public String getCerNo() {
		return cerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.CER_NO
	 * @param cerNo  the value for T_CUM_REGBINDCARD.CER_NO
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setCerNo(String cerNo) {
		this.cerNo = cerNo == null ? null : cerNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.OPEN_PHONE
	 * @return  the value of T_CUM_REGBINDCARD.OPEN_PHONE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public String getOpenPhone() {
		return openPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.OPEN_PHONE
	 * @param openPhone  the value for T_CUM_REGBINDCARD.OPEN_PHONE
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setOpenPhone(String openPhone) {
		this.openPhone = openPhone == null ? null : openPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.STAT
	 * @return  the value of T_CUM_REGBINDCARD.STAT
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public String getStat() {
		return stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.STAT
	 * @param stat  the value for T_CUM_REGBINDCARD.STAT
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setStat(String stat) {
		this.stat = stat == null ? null : stat.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUM_REGBINDCARD.REMARK
	 * @return  the value of T_CUM_REGBINDCARD.REMARK
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUM_REGBINDCARD.REMARK
	 * @param remark  the value for T_CUM_REGBINDCARD.REMARK
	 * @mbggenerated  Tue Jan 21 20:43:13 CST 2014
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}