package com.tisson.entity.bis;

public class SymError {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SYM_ERROR.ERROR_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String errorCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SYM_ERROR.ERROR_INFO
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String errorInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SYM_ERROR.MODULE_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String moduleCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SYM_ERROR.ERROR_LEVEL
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String errorLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SYM_ERROR.HANDLER
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String handler;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SYM_ERROR.STAT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String stat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SYM_ERROR.CODE_OUT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String codeOut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SYM_ERROR.INFO_OUT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	private String infoOut;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SYM_ERROR.ERROR_CODE
	 * @return  the value of T_SYM_ERROR.ERROR_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getErrorCode() {
		return errorCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SYM_ERROR.ERROR_CODE
	 * @param errorCode  the value for T_SYM_ERROR.ERROR_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode == null ? null : errorCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SYM_ERROR.ERROR_INFO
	 * @return  the value of T_SYM_ERROR.ERROR_INFO
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getErrorInfo() {
		return errorInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SYM_ERROR.ERROR_INFO
	 * @param errorInfo  the value for T_SYM_ERROR.ERROR_INFO
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setErrorInfo(String errorInfo) {
		this.errorInfo = errorInfo == null ? null : errorInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SYM_ERROR.MODULE_CODE
	 * @return  the value of T_SYM_ERROR.MODULE_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getModuleCode() {
		return moduleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SYM_ERROR.MODULE_CODE
	 * @param moduleCode  the value for T_SYM_ERROR.MODULE_CODE
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setModuleCode(String moduleCode) {
		this.moduleCode = moduleCode == null ? null : moduleCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SYM_ERROR.ERROR_LEVEL
	 * @return  the value of T_SYM_ERROR.ERROR_LEVEL
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getErrorLevel() {
		return errorLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SYM_ERROR.ERROR_LEVEL
	 * @param errorLevel  the value for T_SYM_ERROR.ERROR_LEVEL
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setErrorLevel(String errorLevel) {
		this.errorLevel = errorLevel == null ? null : errorLevel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SYM_ERROR.HANDLER
	 * @return  the value of T_SYM_ERROR.HANDLER
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getHandler() {
		return handler;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SYM_ERROR.HANDLER
	 * @param handler  the value for T_SYM_ERROR.HANDLER
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setHandler(String handler) {
		this.handler = handler == null ? null : handler.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SYM_ERROR.STAT
	 * @return  the value of T_SYM_ERROR.STAT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getStat() {
		return stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SYM_ERROR.STAT
	 * @param stat  the value for T_SYM_ERROR.STAT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setStat(String stat) {
		this.stat = stat == null ? null : stat.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SYM_ERROR.CODE_OUT
	 * @return  the value of T_SYM_ERROR.CODE_OUT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getCodeOut() {
		return codeOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SYM_ERROR.CODE_OUT
	 * @param codeOut  the value for T_SYM_ERROR.CODE_OUT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setCodeOut(String codeOut) {
		this.codeOut = codeOut == null ? null : codeOut.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SYM_ERROR.INFO_OUT
	 * @return  the value of T_SYM_ERROR.INFO_OUT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public String getInfoOut() {
		return infoOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SYM_ERROR.INFO_OUT
	 * @param infoOut  the value for T_SYM_ERROR.INFO_OUT
	 * @mbggenerated  Mon Jan 27 13:59:45 CST 2014
	 */
	public void setInfoOut(String infoOut) {
		this.infoOut = infoOut == null ? null : infoOut.trim();
	}
}