package com.tisson.dao.bis;

import com.tisson.entity.bis.CumInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CumInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_INFO
	 * @mbggenerated  Tue Jan 21 10:18:49 CST 2014
	 */
	@Delete({ "delete from T_CUM_INFO",
			"where CUST_ID = #{custId,jdbcType=DECIMAL}" })
	int deleteByPrimaryKey(Long custId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_INFO
	 * @mbggenerated  Tue Jan 21 10:18:49 CST 2014
	 */
	@Insert({
			"insert into T_CUM_INFO (CUST_ID, CUST_CODE, ",
			"CUST_TYPE, CUST_SEX, ",
			"CUST_NAME, CUST_PWD, ",
			"AREA_CODE, CERT_TYPE, ",
			"CERT_CODE, PRTN_ID, ",
			"VIP_LEV, AUTH_LEV, ",
			"EFF_DATE, EXP_DATE, STAT, ",
			"OPER_FLAG, BUSI_CODE, ",
			"SVR_CODE, TAXES_FLAG, ",
			"ACTION_TYPE, CHANNEL_TYPE)",
			"values (#{custId,jdbcType=DECIMAL}, #{custCode,jdbcType=VARCHAR}, ",
			"#{custType,jdbcType=VARCHAR}, #{custSex,jdbcType=CHAR}, ",
			"#{custName,jdbcType=VARCHAR}, #{custPwd,jdbcType=VARCHAR}, ",
			"#{areaCode,jdbcType=VARCHAR}, #{certType,jdbcType=VARCHAR}, ",
			"#{certCode,jdbcType=VARCHAR}, #{prtnId,jdbcType=DECIMAL}, ",
			"#{vipLev,jdbcType=VARCHAR}, #{authLev,jdbcType=VARCHAR}, ",
			"#{effDate,jdbcType=DATE}, #{expDate,jdbcType=DATE}, #{stat,jdbcType=CHAR}, ",
			"#{operFlag,jdbcType=VARCHAR}, #{busiCode,jdbcType=VARCHAR}, ",
			"#{svrCode,jdbcType=VARCHAR}, #{taxesFlag,jdbcType=CHAR}, ",
			"#{actionType,jdbcType=VARCHAR}, #{channelType,jdbcType=VARCHAR})" })
	int insert(CumInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_INFO
	 * @mbggenerated  Tue Jan 21 10:18:49 CST 2014
	 */
	@InsertProvider(type = CumInfoSqlProvider.class, method = "insertSelective")
	int insertSelective(CumInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_INFO
	 * @mbggenerated  Tue Jan 21 10:18:49 CST 2014
	 */
	@Select({
			"select",
			"CUST_ID, CUST_CODE, CUST_TYPE, CUST_SEX, CUST_NAME, CUST_PWD, AREA_CODE, CERT_TYPE, ",
			"CERT_CODE, PRTN_ID, VIP_LEV, AUTH_LEV, EFF_DATE, EXP_DATE, STAT, OPER_FLAG, ",
			"BUSI_CODE, SVR_CODE, TAXES_FLAG, ACTION_TYPE, CHANNEL_TYPE",
			"from T_CUM_INFO", "where CUST_ID = #{custId,jdbcType=DECIMAL}" })
	@Results({
			@Result(column = "CUST_ID", property = "custId", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "CUST_CODE", property = "custCode", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CUST_TYPE", property = "custType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CUST_SEX", property = "custSex", jdbcType = JdbcType.CHAR),
			@Result(column = "CUST_NAME", property = "custName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CUST_PWD", property = "custPwd", jdbcType = JdbcType.VARCHAR),
			@Result(column = "AREA_CODE", property = "areaCode", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CERT_TYPE", property = "certType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CERT_CODE", property = "certCode", jdbcType = JdbcType.VARCHAR),
			@Result(column = "PRTN_ID", property = "prtnId", jdbcType = JdbcType.DECIMAL),
			@Result(column = "VIP_LEV", property = "vipLev", jdbcType = JdbcType.VARCHAR),
			@Result(column = "AUTH_LEV", property = "authLev", jdbcType = JdbcType.VARCHAR),
			@Result(column = "EFF_DATE", property = "effDate", jdbcType = JdbcType.DATE),
			@Result(column = "EXP_DATE", property = "expDate", jdbcType = JdbcType.DATE),
			@Result(column = "STAT", property = "stat", jdbcType = JdbcType.CHAR),
			@Result(column = "OPER_FLAG", property = "operFlag", jdbcType = JdbcType.VARCHAR),
			@Result(column = "BUSI_CODE", property = "busiCode", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SVR_CODE", property = "svrCode", jdbcType = JdbcType.VARCHAR),
			@Result(column = "TAXES_FLAG", property = "taxesFlag", jdbcType = JdbcType.CHAR),
			@Result(column = "ACTION_TYPE", property = "actionType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CHANNEL_TYPE", property = "channelType", jdbcType = JdbcType.VARCHAR) })
	CumInfo selectByPrimaryKey(Long custId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_INFO
	 * @mbggenerated  Tue Jan 21 10:18:49 CST 2014
	 */
	@UpdateProvider(type = CumInfoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(CumInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUM_INFO
	 * @mbggenerated  Tue Jan 21 10:18:49 CST 2014
	 */
	@Update({ "update T_CUM_INFO",
			"set CUST_CODE = #{custCode,jdbcType=VARCHAR},",
			"CUST_TYPE = #{custType,jdbcType=VARCHAR},",
			"CUST_SEX = #{custSex,jdbcType=CHAR},",
			"CUST_NAME = #{custName,jdbcType=VARCHAR},",
			"CUST_PWD = #{custPwd,jdbcType=VARCHAR},",
			"AREA_CODE = #{areaCode,jdbcType=VARCHAR},",
			"CERT_TYPE = #{certType,jdbcType=VARCHAR},",
			"CERT_CODE = #{certCode,jdbcType=VARCHAR},",
			"PRTN_ID = #{prtnId,jdbcType=DECIMAL},",
			"VIP_LEV = #{vipLev,jdbcType=VARCHAR},",
			"AUTH_LEV = #{authLev,jdbcType=VARCHAR},",
			"EFF_DATE = #{effDate,jdbcType=DATE},",
			"EXP_DATE = #{expDate,jdbcType=DATE},",
			"STAT = #{stat,jdbcType=CHAR},",
			"OPER_FLAG = #{operFlag,jdbcType=VARCHAR},",
			"BUSI_CODE = #{busiCode,jdbcType=VARCHAR},",
			"SVR_CODE = #{svrCode,jdbcType=VARCHAR},",
			"TAXES_FLAG = #{taxesFlag,jdbcType=CHAR},",
			"ACTION_TYPE = #{actionType,jdbcType=VARCHAR},",
			"CHANNEL_TYPE = #{channelType,jdbcType=VARCHAR}",
			"where CUST_ID = #{custId,jdbcType=DECIMAL}" })
	int updateByPrimaryKey(CumInfo record);
}